services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_search_books
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    restart: always
    environment:
      # Pass in the MongoDB URI that uses service name "mongodb"
      MONGO_URI: mongodb://mongodb:27017/search_books

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./frontend:/usr/src/app
    restart: always

volumes:
  mongo_data:
